### ISSUE TITLE
Call to undefined method app\models\User::find()

### ISSUE THREAD

**Issue by rompastompa** [amnah/yii2-user#141]
Hello.

When I try to login with **neo/neo**, I have PHP Fatal Error: in **models\forms\LoginForm.php** call to undefined method **app\models\User::find()** at line 126.

**Comment by amnah** [comment]
Your model classes need to extend the appropriate models in ```\amnah\yii2\user\models```

**Comment by rompastompa** [comment]
After installation I don't change any files, besides config files. For example, **LoginForm.php** extends appropriate model called **Model**.

`class LoginForm extends Model`

**Comment by rompastompa** [comment]
Problem was in config.

**Comment by kFahima** [comment]
Please clearify the solution. I'm also facing tha same problem.

**Comment by diegotejadav** [comment]
Same problem here @kFahima

**Comment by diegotejadav** [comment]
@kFahima I'm using the Yii2-admin, and the problem was solved by configuring the **identityClass** of the user component.
In my case the solution looks like this:
![screen shot 2017-11-10 at 3 04 21 pm](https://user-images.githubusercontent.com/3412546/32676447-ab78c49e-c628-11e7-9ff2-859e1a81439e.png)
