### ISSUE TITLE
unable to create a nested module inside  yii2 user module

### ISSUE THREAD

**Issue by parvvee** [amnah/yii2-user#171]
in app/modules/user/Module.php i am trying to create user favourites. Yii2 user is working fine but when i am trying to create a nested module under user it wont work.

 `          $this->modules = [

            'fav' => [
              'class' => 'app\modules\user\modules\favourites\Module',
            ]

          ];
`

and i can get the module working right ? Any idea

**Comment by amnah** [comment]
Ummm why not just create a new module in ```app/modules/favourites```?

**Comment by parvvee** [comment]
oh my god.. thanks for such a quick reply.. yes i can create a new module. ... Just wanted to check if theres a way we can do this way.. Nothing serious.. Thank you very much ....

**Comment by amnah** [comment]
Hmm [it's possible](http://www.yiiframework.com/doc-2.0/guide-structure-modules.html#nested-modules) but it probably doesn't work out of the box with this particular module.

Specifically it's because I utilize a hack for the urls, eg, people can go to ```user/register``` instead of ```user/default/register```

https://github.com/amnah/yii2-user/blob/master/Module.php#L226-L256

If you want to to make it work, theoretically you can add the favourites to the $validRoutes but I'm not entirely sure. Can't test it right now ...

**Comment by parvvee** [comment]
sure ...no problem.... dropped in to comment to address it..In the meanwhile I will also try to figure it out..Thank you very much..

**Comment by parvvee** [comment]
yes... @amnah  Its working whnen you add  to the @validRoutes.Thank you. Next time will try to read code better before posting something stupid..Thank you.
