### ISSUE TITLE
CRUD functionality doesn't work in admin controller 

### ISSUE THREAD

**Issue by AlaFalaki** [amnah/yii2-user#87]
Hi,
I installed yii2-user and it worked well, but in the "user/admin" URL <i>(or should i say admin controller)</i>, none of the links ( such as <b>create user</b>, <b>view</b>, <b>update</b>, <b>delete</b>) does not work.
All the links will be redirected to <b>user/admin/index</b> route.
By any chance do you know what might cause the problem ?

**Comment by amnah** [comment]
have you enabled pretty URLs?

http://stackoverflow.com/questions/26525320/enable-clean-url-in-yii2

**Comment by AlaFalaki** [comment]
It's kinda weird.
I did enabled prettyURL before.
But yii2-user came to work when i copy/pasted the code from stackoverflow's answer.
Thanks.

**Comment by AlaFalaki** [comment]
I thought about it and now i have a follow up question.
Why this module only works with prettyURL enabled ?

**Comment by amnah** [comment]
It works fine without prettyURL, just set up a fresh installation to test it. 

You probably have a config issue somewhere, but I can't say what because I have no information on your setup. 

Eg, what steps did you take from installation? What does your config file look like? What do your urls look like? Did you set up apache/nginx rewrite properly?

Are you not using prettyURL?

**Comment by AlaFalaki** [comment]
Sry, that was my mistake, i installed a fresh copy and now it works like a charm.
Thanks man.
