### ISSUE TITLE
Overriding

### ISSUE THREAD

**Issue by vicmonmena** [amnah/yii2-user#95]
Hi again!

I'd like to know which is the best way to override this module in case I'd like to:

* add more fields to user model.
* change login redirection when is successfull and depending on user logged role.

Thx!

**Comment by amnah** [comment]
You'll want to [extend the controller/model files](https://github.com/amnah/yii2-user#how-do-i-extend-this-package).

Specifically:

1. Write migration file
2. Override ```User::rules()``` and ```User::attributeLabels()```
3. Override the ```DefaultController::actionLogin()```

**Comment by vicmonmena** [comment]
Hi again!

Following your steps, I've found some doubts about how to do them:

1. Write migration file depends on my new User model class? Do I have to implement it before launch migration?
2. About the link [extend the controller/model files](https://github.com/amnah/yii2-user#how-do-i-extend-this-package): Do I have to create a new Module?

Thanks a lot!

**Comment by amnah** [comment]
1) Migrations don't rely on models. You can just use the ```{{%tableName}}``` syntax. See the [migration file](https://github.com/amnah/yii2-user/blob/master/migrations/m150214_044831_init_user.php#L18) as an example

2) Create whatever you need to. If you need to override/add variables in the module class, then do so. Otherwise just stick with the controller/models
